info.yml
Esta pull-request hace referencia a la tarea: https://github.com/Aparking/AparKing_Backend/issues/53
Realizada por: @laurolmer
Resumen: La intención de esta PR es la de añadir el documento de info.yml según se pide en la asignatura de ISPP para poder asociar el repositorio con BlueJay y que el profesorado pueda auditarlo
=> Añadido info.yml en el backend

.github/workflows/django.yml, info.yml
Esta pull-request hace referencia a la tarea: https://github.com/Aparking/AparKing_Backend/issues/53
Realizada por: @laurolmer
Resumen: Este volcado se hace para que el contenido de info.yml llegue a main para poder conectar el proyecto con el BlueJay se ha traído también los cambios del django.yml
=> Volcado de develop a main con el info.yml

.github/workflows/django.yml, AparKing_Backend/settings.py
configuracion para comprobar la base de datos y las migraciones
=> config: configuracion para comprobar la base de datos y las migraciones

apps/garagement/serializers.py
**Tarea referenciada:** #8 
**Realizada por:** @ivasansan1 
**Resumen:** Este código implementa la creación de anuncios para garajes incluyendo las imágenes y la dirección. El código consta de una base ya implementada por @laurolmer y mi implementación se favorece de ello. Por motivos del diagrama uml la creación se divide en 3 formularios. Uno para la creación del anuncio, otro para la creación de la imagen asociada al anuncio previamente creado y otro a la dirección para el garaje anteriormente creado.
Anotación: No se tienen pruebas unitarias de esta funcionalidad para dejarle vía libre a @MarioArocaPaez.
=> Creación de un anuncio de garaje 

apps/garagement/permissions.py, apps/garagement/serializers.py, apps/garagement/urls.py, apps/garagement/validations.py, apps/garagement/views.py
**Tarea referenciada**: https://github.com/Aparking/AparKing_Backend/issues/9
**Realizada por**: @3ralon
**Resumen**: Este código implementa la edición y borrado de los alquileres de garajes. También se ha hecho uso de Serializers para transformarlo en JSON y así permitir a la API Rest que manipule los datos mejor.
**Anotación**: No se tienen pruebas unitarias de esta funcionalidad para dejarle vía libre a @MarioArocaPaez.
=> Editar y eliminar alquiler de parking

Dockerfile.dev, apps/parking/views.py, docker-compose.yml
Optimización en la configuración de Docker. Con esta mejora, los contenedores arrancarán correctamente al ser iniciados por primera vez, eliminando la necesidad de reiniciarlos manualmente para una configuración adecuada. Esta corrección asegura una experiencia de desarrollo más fluida y eficiente, facilitando el proceso de puesta en marcha del entorno de desarrollo sin interrupciones.
=> Mejora en la Configuración Inicial de Docker para Contenedores

apps/parking/consumers.py, apps/parking/enums.py, apps/parking/filters.py, apps/parking/models.py, apps/parking/templates/parking/room.html, apps/parking/tests.py, apps/parking/urls.py, apps/parking/views.py
Ahora ya podemos ver en tiempo real todas las operaciones que re realicen sobre las plazas de aparcamiento
Ahora ya nada más algún usuario cree una plaza le aparecerá al resto sin necesidad de cargar de nuevo la página, lo mismo pasará con la eliminación y la asignación.
Podéis verlo en: https://uses0-my.sharepoint.com/:v:/g/personal/albperleo_alum_us_es/EWjcemJO-0FBtQ-GjzAnZp8BuwRHyoEI7QEdNBfA4OnI6w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=0Hx5k0
=> Feat/complete map implementation for parking zones/103

AparKing_Backend/settings.py, apps/authentication/urls.py, apps/authentication/views.py
#4 
Funcionalidad base añadida con validaciones básicas.
Cosas que sé que faltan (posiblemente implementarlas en un futuro cercano):
-Que las acciones sean realizables por un admin (pues no contaba con la funcionalidad de login)
-Restricción sobre fecha para la mayoría de edad de los usuarios
-Refactorización general
-Cambiar los estilos para que sean acordes al resto de la aplicación
Para probar la funcionalidad:
En front, usar la ruta users. Clicar sobre el nombre de un usuario para probar las funcionalidades de actualizar y borrar.
Para añadir un nuevo usuario usar la ruta add.
=> Añadir, editar y eliminar usuarios desde admin [Backend]

Populate.json
Borrado de datos en el populate.json de la entidad city, además de borrado del atributo message de la entidad parking puesto que su uso era solo temporal
=> fix: populate.json delete parking entity and messages atribute #113

.github/ISSUE_TEMPLATE/bug-template.md, .github/ISSUE_TEMPLATE/epic-template.md, .github/ISSUE_TEMPLATE/feature-template.md, .github/ISSUE_TEMPLATE/test-template.md
Se agregan las plantillas de:
- bug: para fix y refactor
- feature: nuevas funcionalidades
- test: para testear funcionalidades
- epic: para las épicas (conjunto de funcionalidades relacionadas)
=> Update issue templates

apps/parking/consumers.py, apps/parking/enums.py, apps/parking/filters.py, apps/parking/models.py, apps/parking/templates/parking/room.html, apps/parking/tests.py, apps/parking/urls.py, apps/parking/views.py
Ahora ya podemos ver en tiempo real todas las operaciones que re realicen sobre las plazas de aparcamiento
Ahora ya nada más algún usuario cree una plaza le aparecerá al resto sin necesidad de cargar de nuevo la página, lo mismo pasará con la eliminación y la asignación.
Podéis verlo en: https://uses0-my.sharepoint.com/:v:/g/personal/albperleo_alum_us_es/EWjcemJO-0FBtQ-GjzAnZp8BuwRHyoEI7QEdNBfA4OnI6w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=0Hx5k0
=> Epic/paking management/14

apps/authentication/models.py
He terminado de modificar la entidad user para que el login con el email sea totalmente correcto, ya que no estaba totalmente configurado
=> fix: change username not unique

apps/booking/serializers.py, apps/booking/validations.py, apps/booking/views.py, apps/garagement/urls.py
Referencia a la tarea https://github.com/Aparking/AparKing_Backend/issues/176, en la que se pedía poder hacer una reserva de garaje. 
- Creación de reserva para una disponibilidad de garaje. Tras crear un garaje y crear una disponibilidad de este, un usuario puede henerar una reserva, eligiendo el método de pago que luego @CarmenRuizPorcel implementará. Tras crear la reserva, se impide que otros usuarios o el mismo usuario realice otra reserva para esa disponibilidad de ese garaje.
- Listado de mis reservas. Un usuario puede listar sus reservas de distintas disponibilidades de garajes.
- Detalles de una reserva. Un usuario puede ver los detalles de una reserva específica.
- Borrado de reservas. Un usuario puede cancelar una reserva, permitiendo que otro usuario pueda volver a reservar esa …
=> Gestión de reservas de garajes.

.github/workflows/django.yml
Arreglo actions Codacy análisis
=> fix: actions Codacy analisis

apps/authentication/serializers.py, apps/authentication/urls.py, apps/authentication/views.py, apps/garagement/tests/test_urls.py, apps/garagement/tests/test_views.py
Esta pull-request añade la funcionalidad de traer los datos del usuario desde el backend al frontend.
=> Datos de usuario de backend a frontend

apps/parking/views.py
Tras haber realizado varias pruebas parece que el login y el registro funcionan bien, es cierto que dependiendo de socket se puede observar un pequeño delay en el mapa o incluso un fallo en algunas ocasiones, es por ello que he aprovechado la issue para optimizar algunos aspectos en como se conecta al socket al iniciar sesión y en como crea el mapa.
Ademas he solucionado una errata que había en una url que podría haber generado conflictos.
Realizo este hotfix, tanto a master como develop debido a la urgencia de mejora del rendimiento.
=> fix-login/register/#231

apps/parking/views.py
Tras haber realizado varias pruebas parece que el login y el registro funcionan bien, es cierto que dependiendo de socket se puede observar un pequeño delay en el mapa o incluso un fallo en algunas ocasiones, es por ello que he aprovechado la issue para optimizar algunos aspectos en como se conecta al socket al iniciar sesión y en como crea el mapa.
Ademas he solucionado una errata que había en una url que podría haber generado conflictos.
Realizo este hotfix, tanto a master como develop debido a la urgencia de mejora del rendimiento.
=> Fix login/register/#231

apps/parking/urls.py, apps/parking/views.py
He implentado una función que obtiene tu ubicación y a partir de esta saca las 5 ciudades cercanas a tí, para que puedas realizar búsquedas más efectivas.
=> Search Location

apps/parking/filters.py
En el frontend se ha implementado la desconexión del socket, una limitación de las plazas que obtiene para ahorrar recursos a la par que mantiene la buena experiencia de uso, además se ha introducido un botón para ir a la plaza más cercana.
En el backend he solucionado un error que había con el filtro de parkings.
=> live notifications

apps/authentication/models.py, apps/authentication/serializers.py, apps/authentication/urls.py, apps/authentication/views.py
Añadida funcionalidad para registrar un vehículo por parte del usuario. #240
=> feat: funcionalidad registro de vehiculo #240

apps/authentication/views.py, apps/parking/urls.py, apps/parking/views.py
=> Arreglar cesión de plazas de aparcamiento #255

apps/booking/enums.py, apps/booking/models.py, apps/booking/urls.py, apps/booking/views.py, apps/garagement/views.py
Arreglo de las reservas para que estas se hagan una vez hayas pagado con tarjeta
Arreglo para que las reservas puedan hacerse en efectivo
#261
=> Fix selección método pago en reserva #261

apps/authentication/models.py, apps/parking/models.py, apps/parking/serializers.py, apps/parking/views.py, apps/payment/models.py, apps/payment/views.py
Añadida funcionalidad para añadir una fecha y hora solo en los aparcamientos de tipo cesión. #293 
Se ha arreglado también un bug relacionado con los créditos de los usuario tras pasar la pasarela de pago de la membresía.
=> feat: funcioalidad para añadir fecha y hora a la cesion de aparcamiento

apps/authentication/models.py, apps/payment/models.py, apps/payment/urls.py, apps/payment/views.py
Funcionalidad de compra de creditos
=> feat: compra de créditos

apps/authentication/models.py, apps/authentication/urls.py, apps/authentication/views.py, apps/parking/models.py, apps/parking/views.py, apps/payment/views.py
Creación de listado de vehículos del usuario, con posibilidad de asignar un vehículo como principal, lo cual será permite entre otras cosas poder obtener cesiones de vehículos con los distintos automóviles del usuario según le sea necesario. #312
=> Fix/cesiones y listado vehiculos con eleccion vehiculo/312

apps/authentication/models.py, apps/authentication/urls.py, apps/authentication/views.py, apps/parking/models.py, apps/parking/views.py, apps/payment/views.py
Añadida lógica para conceder crédito a los usuarios que creen de forma correcta una cesion de aparcamiento #24
=> Feat/gestión bonificaciones/24

Populate.json, docker/migrationsInit.sh
arreglo de populate.json para información de ejemplo en la aplicación #326
=> fix: populate.json

apps/authentication/serializers.py, apps/parking/serializers.py
He añadido la validación para que los campos altura, anchura y largo no puedan ser negativos, y he cambio color por un enum.
He puesto también los campos en español para que encaje mejor con el público de la aplicación.
=> Fix validate vehicle form

apps/payment/tests.py, apps/payment/urls.py, apps/payment/views.py
Test completo del modulo payment
=> Test/views payment/356

apps/booking/tests/test_serializers.py, apps/garagement/tests/test_serializers.py
Tests de todos los serializers de esos dos modulos
=> Serializers tests Garagement Booking

apps/garagement/tests/test_views.py
Test de la creación de garajes: view; url; serializer
=> Test: CRUD garaje
